# Copyright 2021 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

name: "Release"

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The release version to be used'
        required: false
      next-version:
        description: 'The next version to be used (make sure to use SNAPSHOT)'
        required: false

jobs:
  release:
    if: github.repository == 'xskipper-io/xskipper'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Xskipper repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install Python packages (Python 3.7)
        run: |
          python3.7 -m pip install pyspark==3.2.0
      - name: Run Python tests
        run: python3.7 run-tests.py
      - if: |
          github.event.inputs.release-version != '' &&
          github.event.inputs.next-version != ''
        name: Release
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          GIT_REF: ${{ matrix.branch }}
        run: |
          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          git clean -f
          git config --global user.email "xskipperci@gmail.com"
          git config --global user.name "Xskipper CI"
          # capture release version before doing release for site publishing
          export SITE_VERSION=${{ github.event.inputs.release-version }}
          [[ -z "$SITE_VERSION" ]] && echo "ERROR: SITE_VERSION var is empty" && exit -1
          # set the env variable to be available for the next step
          echo "SITE_VERSION=$SITE_VERSION" >> $GITHUB_ENV
          build/sbt 'release release-version ${{ github.event.inputs.release-version }} next-version ${{ github.event.inputs.next-version }}'
          git push
      - if: |
          github.event.inputs.release-version == '' &&
          github.event.inputs.next-version == ''
        name: Release
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          GIT_REF: ${{ matrix.branch }}
        run: |
          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          git clean -f
          git config --global user.email "xskipperci@gmail.com"
          git config --global user.name "Xskipper CI"
          # capture release version before doing release for site publishing
          export SITE_VERSION=`sed -n 's/version in ThisBuild := "\(.*\)-SNAPSHOT"/\1/p' version.sbt`
          [[ -z "$SITE_VERSION" ]] && echo "ERROR: SITE_VERSION var is empty" && exit -1
          # set the env variable to be available for the next step
          echo "SITE_VERSION=$SITE_VERSION" >> $GITHUB_ENV
          build/sbt 'release with-defaults'
          git push
      - name: Publish site version
        working-directory: ./site
        run: |
          pip install mkdocs-material
          pip install mkdocs-redirects
          pip install mkdocs-markdownextradata-plugin
          pip install mike
          git config --global user.email "xskipperci@gmail.com"
          git config --global user.name "Xskipper CI"
          git fetch origin xskipper-site
          mike deploy --push --remote origin --branch xskipper-site ${{ env.SITE_VERSION }}
          mike set-default --push --remote origin --branch xskipper-site ${{ env.SITE_VERSION }}
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
